import {
  LayoutDashboard,
  Wallet,
  PieChart,
  Target,
  Bot,
  Settings,
  User,
  ArrowDown,
  ArrowUp,
  ChevronRight,
  ChevronLeft,
  Car,
  Asterisk,
  Coffee,
  ShoppingBag,
  CreditCard,
  Plus,
  Landmark,
  Smartphone,
  Banknote,
  MoreHorizontal,
  ArrowRightLeft,
  Trash2,
  Edit2,
  X,
  Clock,
  History,
  TrendingUp,
  Users,
  Eye,
  EyeOff,
  ListFilter,
  Check,
  Calendar,
  Utensils,
  Zap,
  Film,
  Heart,
  Home,
  Bus,
  Coins,
  Star,
  AlertTriangle,
  PiggyBank,
  Repeat,
  LogOut,
  List,
  Trophy,
  Sparkles,
  CircleDollarSign,
  MoreVertical,
  CalendarClock,
  CheckCircle2,
  PartyPopper,
  Plane,
  Laptop,
  Baby,
  Gem,
  Briefcase,
  GraduationCap,
  AlertCircle,
  MapPin,
  Flag,
  Bell,
  CalendarCheck,
  RefreshCw,
  Power,
  Search,
  Wifi,
  Droplets,
  Lightbulb,
  Music,
  Tv,
  FileText,
  Info,
  ImageIcon,
  ScanLine,
  Store,
  Globe,
  Wheat,
  CarTaxiFront,
  Tent,
  Sun,
  Moon,
  Cloud,
  Download,
  Send,
  Table2,
  Lock,
  Inbox,
  MessageSquare,
  Shield,
  HelpCircle,
  Camera,
} from "lucide-react"

export const Icons = {
  Dashboard: LayoutDashboard,
  Wallet: Wallet,
  Budget: PieChart,
  Goals: Target,
  AI: Bot,
  Settings: Settings,
  User: User,
  ArrowDown: ArrowDown,
  ArrowUp: ArrowUp,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Car: Car,
  Emergency: Asterisk,
  Coffee: Coffee,
  Shopping: ShoppingBag,
  CreditCard: CreditCard,
  Plus: Plus,
  Bank: Landmark,
  Phone: Smartphone,
  Cash: Banknote,
  More: MoreHorizontal,
  Transfer: ArrowRightLeft,
  Delete: Trash2,
  Edit: Edit2,
  Close: X,
  Clock: Clock,
  History: History,
  TrendingUp: TrendingUp,
  Users: Users,
  Eye: Eye,
  EyeOff: EyeOff,
  Filter: ListFilter,
  Check: Check,
  Calendar: Calendar,
  Utensils: Utensils,
  Zap: Zap,
  Film: Film,
  Heart: Heart,
  Home: Home,
  Bus: Bus,
  Coins: Coins,
  Star: Star,
  Alert: AlertTriangle,
  PiggyBank: PiggyBank,
  Repeat: Repeat,
  LogOut: LogOut,
  List: List,
  Trophy: Trophy,
  Sparkles: Sparkles,
  RoundUp: CircleDollarSign,
  MoreVertical: MoreVertical,
  CalendarClock: CalendarClock,
  CheckCircle: CheckCircle2,
  Celebration: PartyPopper,
  Plane: Plane,
  Laptop: Laptop,
  Baby: Baby,
  Ring: Gem,
  Briefcase: Briefcase,
  Education: GraduationCap,
  Error: AlertCircle,
  MapPin: MapPin,
  Flag: Flag,
  Bell: Bell,
  CalendarCheck: CalendarCheck,
  Recurring: RefreshCw,
  Power: Power,
  Search: Search,
  Wifi: Wifi,
  Water: Droplets,
  Electricity: Lightbulb,
  Music: Music,
  Tv: Tv,
  Note: FileText,
  Info: Info,
  Camera: Camera,
  Scan: ScanLine,
  Image: ImageIcon,
  Store: Store,
  Globe: Globe,
  Briefcase2: Briefcase, // For Salary alias if needed
  Freelance: Laptop,
  SideHustle: Zap,
  Teff: Wheat,
  Bajaji: CarTaxiFront,
  Iddir: Tent,
  Sun: Sun,
  Moon: Moon,
  Cloud: Cloud,
  Download: Download,
  Send: Send,
  Table: Table2,
  Lock: Lock,
  Inbox: Inbox,
  Feedback: MessageSquare,
  Shield: Shield,
  Help: HelpCircle,
}
